config/routes.rb
Rails.application.routes.draw do
  devise_for :admins
  devise_for :users
  resources :tours do
  	resources :reviews
  end
  
  root "tours#index"
  get '/peta', to: 'pages#peta'
end

app/models/admin.rb
class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :lockable 
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :tours
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
end

app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :tour
  belongs_to :user
end

app/models/tour.rb
class Tour < ActiveRecord::Base
	has_many :reviews
	belongs_to :category
	belongs_to :user
	validates :judul, presence: true, length: {minimum: 5}
  	validates :latitude, presence: true
  	validates :longitude, presence: true
  	validates :konten, presence: true
  	validates :category_id, presence: true
  	require 'carrierwave/orm/activerecord'
  	mount_uploader :gambar, GambarUploader
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
   has_many :tours
   has_many :reviews
     def login=(login)
    @login = login
  end

  def login
    @login || self.username || self.email
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:username, :email, :password, :password_confirmation, :remember_me) }
    devise_parameter_sanitizer.for(:sign_in) { |u| u.permit(:login, :username, :email, :password, :remember_me) }
    devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:username, :email, :password, :password_confirmation, :current_password) }
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController


	def peta
		@tours = Tour.all
		@hash = Gmaps4rails.build_markers(@tours) do |tour, marker|

  		marker.lat tour.latitude
  		marker.lng tour.longitude
      marker.infowindow render_to_string(:partial => "info", :locals => { :object => tour})
      marker.json({:id => tour.id})


      if tour.category_id == 1
  		marker.picture({
      		"url"=> "http://localhost:3000/assets/alam.png",
      		"width" => 36,
      		"height" => 36
      	})
  		elsif tour.category_id == 2
		marker.picture({
      		"url"=> "http://localhost:3000/assets/museum.png",
      		"width" => 36,
      		"height" => 36
      	})
		elsif tour.category_id == 3
		marker.picture({
      		"url"=> "http://localhost:3000/assets/book.png",
      		"width" => 36,
      		"height" => 36
      	})
		elsif tour.category_id == 4
		marker.picture({
      		"url"=> "http://localhost:3000/assets/market.png",
      		"width" => 36,
      		"height" => 36
      	})
		else
		marker.picture({
      		"url"=> "http://localhost:3000/assets/star.png",
      		"width" => 36,
      		"height" => 36
      	})

  		end

		end
	end
  def info
  @tour = Tour.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	
	def create
		@tour = Tour.find(params[:tour_id])
		@review = @tour.reviews.create(params[:review].permit(:body).merge(:username => current_user.username))
		redirect_to tour_path(@tour)
	end

	def destroy
		if current_user.admin?
	    @tour = Tour.find(params[:tour_id])
	    @review = @tour.reviews.find(params[:id])
	    @review.destroy
	       redirect_to tour_path(@tour)
	       else
 		redirect_to tour_path(@tour), :flash => { :success => "Anda tidak diperkenankan menghapus informasi" }
		end
	end
end

app/controllers/tours_controller.rb
class ToursController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		if params[:category].blank?
			@tours = Tour.all.order("created_at DESC")
		else
			@category_id = Category.find_by(name: params[:category]).id
				@tours = Tour.where(category_id: @category_id).order("created_at DESC")
		end
	end
	def new
		if current_user.admin?
 		 @tour = current_user.tours.build
 		else
 		redirect_to root_path(@user), :flash => { :success => "Anda tidak diperkenankan membuat lokasi baru" }
		end
		
	end

	def create
		@tour = current_user.tours.build(tour_params)
		@tour.save
		if @tour.save
			redirect_to @tour
		else
			render 'new'
		end
	end
	def show
		@tour = Tour.find(params[:id])
	end

	def edit
		if current_user.admin?
 		@tour = Tour.find(params[:id])
 		else
 		redirect_to root_path(@user), :flash => { :success => "Anda tidak diperkenankan mengubah informasi" }
		end
		
	end
 
	def update
		@tour = Tour.find(params[:id])
		if @tour.update(params[:tour].permit(:judul,:latitude,:longitude,:konten, :category_id, :gambar))
			redirect_to @tour
		else
			render 'edit'
		end
	end

	def destroy
		if current_user.admin?
	    @tour = Tour.find(params[:id])
	    @tour.destroy
	       redirect_to tours_path
	       else
 		redirect_to root_path(@user), :flash => { :success => "Anda tidak diperkenankan menghapus informasi" }
		end
	end

	private
	def tour_params
		params.require(:tour).permit(:judul,:latitude,:longitude,:konten, :category_id, :gambar)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/tours_helper.rb
module ToursHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Sistem Informasi Pariwisata DIY</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id="sidebar">
    <div id="logo">
      <%= link_to root_path do %>
      <%= image_tag "logo.svg" %>
      <% end %>
    </div>
    <ul>
      <li class="category"><%= link_to "Home", root_path %></li>
      <li class="category"><%= link_to "Peta Wisata", peta_path %></li>
    </ul>
 
    <ul>
      <li class="category"><%= link_to "Semua", root_path %></li>
      <% Category.all.each do |category| %>
      <li class="category"><%= link_to category.name, tours_path(category: category.name) %></li>
      <% end %>
    </ul>
    <p class="sign_in">
      <ul>
        <% if user_signed_in? %>
        <li class="category">
          <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>        
        </li>
        <% else %>
        <li class="category">
          <%= link_to('Login', new_user_session_path)  %>  
        </li>
        <% end %>
      </ul>
    </p>
  </div>

  <div id="main_content">
    <div id="main_content header">
      <div class="buttons">
        <% if user_signed_in? %>
        <%= link_to "New Post", new_tour_path, class: "button" %>
        <% end %>
      </div>
    </div>
    <% flash.each do |name, msg| %>
    <%= content_tag(:div, msg, class: "alert") %>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>

app/views/pages/_info.html.erb
<%= image_tag (object).gambar_url, class: "img-map" %><br>
<%= link_to (object).judul, tour_path(object) %><br>


app/views/pages/info.html.erb
<%= @tour.judul %>
<%= link_to 'Lihat Detail', tour_path(object) %>

app/views/pages/peta.html.erb
<script src="//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry" type="text/javascript"></script>
<script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js' type='text/javascript'></script>

<div style='width: 1000px;'>
	<div id="map" style='width: 1000px; height: 500px;'></div>
</div>

<div class="keterangan">
	<h2>Keterangan</h2>
	<img src='http://localhost:3000/assets/museum.png'> Museum/ Monumen 
  	<img src='http://localhost:3000/assets/book.png'> Wahana Pendidikan 
  	<img src='http://localhost:3000/assets/alam.png'> Wisata Alam 
  	<img src='http://localhost:3000/assets/market.png'> Wisata Belanja 
  	<img src='http://localhost:3000/assets/star.png'> Lain-lain
</div>

<script type="text/javascript">
	handler = Gmaps.build('Google');
	handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
	markers = handler.addMarkers(<%=raw @hash.to_json %>);
	handler.bounds.extendWith(markers);
	handler.fitMapToBounds();
	});
</script>



app/views/reviews/_form.html.erb
<%= form_for([@tour, @tour.reviews.build]) do |f| %>
<%= f.label :review %><br>
<%= f.text_area :body %><br>
<%= f.submit %>
<% end %>

app/views/reviews/_review.html.erb
<div class="comment clearfix">
  <div class="comment_content">
    <p class="comment_name"><strong><%= review.username %></strong></p>
    <p class="comment_body"><%= review.body %></p>
    <p class="comment_time"><%= time_ago_in_words(review.created_at) %> ago</p> 
  </div>
  <% if user_signed_in? %>
  <p><%= link_to 'Delete', [review.tour, review], method: :delete, class: "button", data: { confirm: 'Are you sure?'} %></p>
  <% end %>
</div>

app/views/tours/_form.html.erb
<%= form_for @tour, :html => { :multipart => true } do |f| %>
<% if @tour.errors.any? %>
<div id="errors">
  <h2><%= pluralize(@tour.errors.count, "error") %> prevented this tour from saving:</h2>
  <ul>
    <% @tour.errors.full_messages.each do |msg| %>
    <li><%= msg %></li>
    <% end %>
  </ul>
</div>
<% end %>

<%= f.file_field :gambar %>
<p>
  <%= f.label :judul %><br>
	<%= f.text_field :judul %>
</p>
<p>
	<%= f.label :category_id %><br>
	<%= f.collection_select :category_id, Category.all, :id, :name, { prompt: "Pilih Kategori" } %>
</p>
<p>
	<%= f.label :latitude %><br>
	<%= f.text_field :latitude %>
</p>
<p>
	<%= f.label :longitude %><br>
	<%= f.text_field :longitude %>
</p>
<p>
	<%= f.label :konten %><br>
	<%= f.text_area :konten %>
</p>
<%= f.submit %>
<% end %>

app/views/tours/edit.html.erb
<h2>Edit Konten</h2>
<%= render 'form' %>

app/views/tours/index.html.erb
<% @tours.each do |tour| %>
<div class="post_wrapper">
	<h2 class="title"><%= link_to tour.judul, tour %></h2>
	<p class="date"><%= tour.created_at.strftime("%d %B %Y") %> 
</div>
<% end %>

app/views/tours/new.html.erb
<h1>New Form</h1>
<%= render 'form' %>

app/views/tours/show.html.erb
<div id="post_content">
<h1 class="title">
  <%= @tour.judul %>
</h1>

<p class="date_and_author">
  Published on <%= time_ago_in_words(@tour.created_at) %> ago - <a href='#comments'><%= @tour.reviews.count %> Review </a>
  <% if user_signed_in? %>
  <%= link_to 'Edit', edit_tour_path(@tour) %> |
  <%= link_to 'Delete', tour_path(@tour), method: :delete, data: { confirm: 'Are you sure?' } %>
  <% end %>
</p>
<br>
<p class="body">
  <%= image_tag @tour.gambar_url, class: "img-post" %><br>
  <%= @tour.latitude %><br>
	<%= @tour.longitude %><br>
	<%= @tour.konten %>
</p>
<div id="comments">
  <h2>Review Pengunjung</h2>
    <%= render @tour.reviews %>
  <% if user_signed_in? %>
    <%= render "reviews/form" %>
  <% else %>
    <p><%= link_to('Login', new_user_session_path)  %>  or <%= link_to('Registrasi', new_user_registration_path) %> untuk memberi review</p>
  <% end %>	
</div>
</div>